# Add 'test' label to any change in tests
test:
- */src/test/**

# Add 'actions' label to any change within the github actions
actions:
- .github/**

# Add 'book' label to any change to src files within the bookMicroservice
book:
- bookMicroservice/**
