version: "3.8"

services:

  postgresql:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"

  eureka:
    build:
      context: eurekaServer
      dockerfile: dockerfile
    restart: on-failure

  book:
    build:
      context: bookMicroservice
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - postgresql
      - eureka
  authorization:
    build:
      context: authorizationMicroservice
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - postgresql
      - eureka
  borrow:
    build:
      context: borrowOperationMicroservice
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - postgresql
      - eureka
  customer:
    build:
      context: customerMicroservice
      dockerfile: dockerfile
    restart: on-failure
    depends_on:
      - postgresql
      - eureka

